spring:
  application:
    name: 05-Springboot-DataJpa-app
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/shubham
    password: mr.shubs
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true